name: Repository Info Action
description: Get repository info such as the repository name and owner.

inputs:
  repo:
    description: 'The full name of the repository (with the owner), e.g., owner/repo.'
    default: ${{ github.repository }}
  owner:
    description: 'The owner of the repository.'
    default: ${{ github.repository_owner }}

outputs:
  repo-full-name:
    description: 'The full name of the repository (with the owner).'
    value: ${{ steps.set-full-name.outputs.repo-full-name }}
  repo-name:
    description: 'The name of the repository (without the owner).'
    value: ${{ steps.get-repo-name.outputs.repo-name }}
  repo-owner:
    description: 'The owner of the repository.'
    value: ${{ steps.get-repo-owner.outputs.repo-owner }}
  repo-url:
    description: 'The URL of the repository.'
    value: ${{ steps.get-repo-url.outputs.repo-url }}

runs:
  using: 'composite'
  steps:
    - name: Get repository name
      id: get-repo-name
      shell: bash
      env:
        REPO: ${{ inputs.repo || github.repository }}
      run: |
        repo_name="${REPO#*/}"
        echo "repo-name=$repo_name" >> "$GITHUB_OUTPUT"
        echo "::info::Repository name: $repo_name"
    - name: Get repository owner
      id: get-repo-owner
      shell: bash
      env:
        OWNER: ${{ inputs.owner || github.repository_owner }}
      run: |
        repo_owner="${OWNER:-$GITHUB_REPOSITORY_OWNER}"
        echo "repo-owner=$repo_owner" >> "$GITHUB_OUTPUT"
        echo "::info::Repository owner: $repo_owner"
    - name: Get repository URL
      id: get-repo-url
      shell: bash
      run: |
        repo_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
        echo "repo-url=$repo_url" >> "$GITHUB_OUTPUT"
        echo "::info::Repository URL: $repo_url"
    - name: Validate repository full name
      id: set-full-name
      shell: bash
      env:
        REPO_NAME: ${{ steps.get-repo-name.outputs.repo-name }}
        REPO_OWNER: ${{ steps.get-repo-owner.outputs.repo-owner }}
      run: |
        repo_full_name="${REPO_OWNER}/${REPO_NAME}"
        if [ "$repo_full_name" != "${GITHUB_REPOSITORY}" ]; then
          echo "::error::The provided repository full name ($repo_full_name) does not match the current repository ($GITHUB_REPOSITORY)."
          exit 1
        fi
        echo "repo-full-name=$repo_full_name" >> "$GITHUB_OUTPUT"
        echo "::info::Repository full name: $repo_full_name"
