name: Watching the Watchers
description: A workflow to handle events when someone watches a repository. It can create a welcome issue for the watcher if they are a member of the organization, and provides outputs that can be used in subsequent steps or jobs to customize the welcome message and determine if the watcher is an organization member.

inputs:
  create-issue:
    description: 'Whether to create a welcome issue for the watcher (if they are a member of the organization).'
    required: false
  job-summary:
    description: 'Whether to add a job summary with the welcome message for the watcher.'
    required: false
  job-summary-heading-level:
    description: 'The heading level to use for the welcome message in the job summary (1-6).'
    required: false
    default: '1'
  github-token:
    description: 'GitHub Personal Access Token with repo scope for creating issues.'
    required: true

outputs:
  message-heading:
    description: 'The heading of the welcome message created for the watcher.'
    value: ${{ steps.welcome-message.outputs.message-heading }}
  message-body-base64:
    description: 'The body of the welcome message created for the watcher, encoded in base64.'
    value: ${{ steps.welcome-message.outputs.message-body-base64 }}
  is-organization-member:
    description: 'Whether the watcher is a member of the organization.'
    value: ${{ steps.is-org-member.outputs.result }}

runs:
  using: composite
  steps:
    - name: Log Watch Event
      uses: actions/github-script@v9
      with:
        script: |
          core.notice(`Repository is being watched by ${context.actor}.`);
          core.info(`Event sender: ${JSON.stringify(context.payload.sender)}`);

    - name: Create Welcome Message
      id: welcome-message
      uses: actions/github-script@v9
      env:
        JOB_SUMMARY: ${{ inputs.job-summary == 'true' }}
        JOB_SUMMARY_HEADING_LEVEL: ${{ inputs.job-summary-heading-level }}
        REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
      with:
        script: |
          const headingLevelInput = process.env.JOB_SUMMARY_HEADING_LEVEL || '1';
          let validHeadingLevel = 1;
          try {
            const messageHeadingLevel = parseInt(headingLevelInput, 10);
            validHeadingLevel = Math.min(Math.max(messageHeadingLevel, 1), 6);
          } catch (error) {
            core.warning(`Invalid job summary heading level provided: ${headingLevelInput}. Defaulting to ${validHeadingLevel}.`);
          }
          core.debug(`Using heading level ${validHeadingLevel} for job summary heading.`);
          const messageHeading = process.env.STEP_SUMMARY_HEADING || `Welcome, @${context.payload.sender.login || context.actor}!`;
          const stargazerLink = `[stargazers](${process.env.REPOSITORY_URL}/stargazers)`;
          const messageStargazer = `See ${stargazerLink} to see all watchers.`;
          const messageBody = process.env.STEP_SUMMARY_BODY || [
            'Thanks for watching this repository! We appreciate your interest and support.',
            '\nIf you have any questions, suggestions, or just want to say hi, feel free to open an issue or join the discussions.',
            `\n${messageStargazer}`,
          ].join('\n');
          const messageBodyBase64 = Buffer.from(messageBody, 'utf-8').toString('base64');
          core.debug(`Welcome message heading: ${messageHeading}`);
          core.debug(`Welcome message body: ${messageBody}`);
          core.debug(`Encoded welcome message body in base64: ${messageBodyBase64}`);
          core.setOutput('message-heading', messageHeading);
          core.setOutput('message-body-base64', messageBodyBase64);
          const addJobSummary = Boolean(process.env.JOB_SUMMARY);
          core.info(`Add job summary: ${addJobSummary}`);
          if (addJobSummary) {
            try {
              const summary = [
                `${'#'.repeat(validHeadingLevel)} ${messageHeading}`,
                `\n${messageBody}`,
              ].join('\n');
              await core.summary.addRaw(summary).write();
            } catch (error) {
              core.warning(`Failed to add job summary: ${error.message}`);
            }
          }

    - name: Check if Watcher is an Organization Member
      id: is-org-member
      uses: actions/github-script@v9
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const username = context.payload?.sender?.login || context.actor;
          if (!username) {
            core.warning("No username found for the watcher.");
            return;
          }
          const org = context.repo.owner;
          try {
            const { data: membership } = await github.rest.orgs.getMembershipForUser({
              org,
              username,
            });
            const isMember = membership.state === 'active';
            core.info(`Is watcher '${username}' a member of the organization '${org}'? ${isMember}`);
            return isMember;
          } catch (error) {
            if (error.status === 403) {
              core.warning(`Insufficient permissions to check if watcher '${username}' is a member of the organization '${org}'. Ensure the provided GitHub token has the necessary scopes.`);
              return false;
            }
            if (error.status === 404) {
              core.warning(`Watcher '${username}' is not a member of the organization '${org}'.`);
              return false;
            }
            throw error;
          }

    - name: Create Welcome Issue
      if: inputs.create-issue == 'true' && steps.is-org-member.outputs.result == 'true'
      uses: actions/github-script@v9
      env:
        MESSAGE_HEADING: ${{ steps.welcome-message.outputs.message-heading }}
        MESSAGE_BODY_BASE64: ${{ steps.welcome-message.outputs.message-body-base64 }}
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const title = process.env.MESSAGE_HEADING;
          const bodyBase64 = process.env.MESSAGE_BODY_BASE64;
          const body = Buffer.from(bodyBase64, 'base64').toString('utf-8');
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            body,
          });
