name: Check if first commit
description: 'Reusable action to check if the current commit is the first commit in the repository.'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: tag
  color: red

outputs:
  is-first-commit:
    description: 'Whether the current commit is the first commit in the repository'
    value: ${{ steps.check-first-commit.outputs.is-first-commit }}

runs:
  using: 'composite'
  steps:
    - name: Check if this is the first commit
      id: check-first-commit
      shell: bash
      env:
        IS_ZERO_EVENT: ${{ github.event.before == '0000000000000000000000000000000000000000' }}
      run: |
        if [ $(git rev-list --count HEAD) -eq 1 ] && [ "$IS_ZERO_EVENT" = "true" ]; then
          echo "This is the first commit."
          echo "is-first-commit=true" >> $GITHUB_OUTPUT
          echo "::notice::This is the first commit in the repository."
        else
          echo "This is not the first commit."
          echo "is-first-commit=false" >> $GITHUB_OUTPUT
        fi
