name: Check if first commit
description: 'Reusable action to check if the current commit is the first commit in the repository.'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: tag
  color: red

inputs:
  commit-count-to-check:
    description: 'The commit count to check against (default: 0).'
    required: false
    default: '0'

outputs:
  is-first-commit:
    description: 'Whether the current commit is the first commit in the repository'
    value: ${{ steps.check-first-commit.outputs.is-first-commit }}

runs:
  using: 'composite'
  steps:
    - name: Check if this is the first commit
      id: check-first-commit
      shell: bash
      env:
        COMMIT_COUNT_TO_CHECK: ${{ inputs.commit-count-to-check || 0 }}
        IS_ZERO_EVENT: ${{ github.event.before == '0000000000000000000000000000000000000000' }}
      run: |
        # Simple arithmetic to check if COMMIT_COUNT_TO_CHECK is a valid number, if not default to 0
        COMMIT_COUNT_TO_CHECK=$(( $COMMIT_COUNT_TO_CHECK + 0 )) || COMMIT_COUNT_TO_CHECK=0
        echo "Commit count to check: $COMMIT_COUNT_TO_CHECK"
        echo "Is zero event: $IS_ZERO_EVENT"
        if [ $COMMIT_COUNT_TO_CHECK -gt 0 ]; then
          commit_count=$(git rev-list --count HEAD)
          echo "Commit count: $commit_count"
          if [ $COMMIT_COUNT_TO_CHECK -eq 1 ] && [ $commit_count -eq 1 ] && [ "$IS_ZERO_EVENT" = "true" ]; then
            echo "This is the first commit."
            echo "is-first-commit=true" >> $GITHUB_OUTPUT
            echo "::notice::This is the first commit in the repository."
          elif [ $COMMIT_COUNT_TO_CHECK -gt 1 ] && [ $commit_count -le "$COMMIT_COUNT_TO_CHECK" ]; then
            echo "This is commit number $commit_count."
            echo "is-first-commit=true" >> $GITHUB_OUTPUT
            echo "::notice::This is commit number $commit_count in the repository."
          else
            echo "This is not the first or specified ($COMMIT_COUNT_TO_CHECK) commit."
            echo "is-first-commit=false" >> $GITHUB_OUTPUT
          fi
        fi
