name: CI Package Update

on:
  push:
    branches: [main]
    paths:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

  workflow_call:
    inputs:
      paths:
        description: 'A newline delimited list of file paths to check for changes (e.g. package.json and package-lock.json).'
        type: string
        default: |
          package.json
          package-lock.json
          CHANGELOG.md
      ignore-authors:
        description: 'A newline delimited list of commit authors to ignore when checking for changes (e.g. semantic-release-bot and github-actions[bot]).'
        type: string
        default: |
          github-actions[bot]
          semantic-release-bot
      action-ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        type: string
    secrets:
      github-token:
        description: 'GitHub Personal Access Token with repo scope for checking commits.'

concurrency:
  group: ${{ github.event_name != 'push' && format('{0}-{1}', github.repository_id, github.ref_name || github.run_id) }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      trigger-update: ${{ steps.has-paths.outputs.trigger-update == 'true' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          sparse-checkout: ${{ inputs.paths }}
          fetch-depth: 2
          persist-credentials: false

      - name: Checkout shared actions repo
        uses: actions/checkout@v7
        with:
          repository: stairwaytowonderland/actions
          path: ./.actions
          ref: ${{ inputs.action-ref }}
          persist-credentials: false
          sparse-checkout: |
            .github/actions

      - name: Check for changed files
        id: has-paths
        uses: ./.actions/.github/actions/changed-files-action
        with:
          paths: ${{ inputs.paths }}
          ignore-authors: ${{ inputs.ignore-authors }}
          ignore-events: push

  package-update:
    name: Update packages
    needs: [setup]
    if: needs.setup.outputs.trigger-update == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch Publish workflow
        if: ${{ (github.event.head_commit.author.name != 'semantic-release-bot' && github.event.head_commit.author.name != 'github-actions[bot]') && !startsWith(github.event.head_commit.message, 'chore(release):') }}
        uses: stairwaytowonderland/simple-workflow-dispatch@main
        with:
          workflow: ci.yaml
