name: CI

on:
  push:
    # Trigger 1: When main branch is updated (respects path ignores)
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

    # Trigger 2: When a version tag is pushed
    tags:
      - 'v*'

  workflow_call:
    inputs:
      fail-on-no-release:
        description: 'Fail the workflow if no release is published (e.g. if there are no relevant commits).'
        type: boolean
        default: true
      publish:
        description: 'Whether to run in publish mode.'
        type: boolean
      tag:
        description: 'Existing release tag to publish (e.g. v1.2.3)'
        type: string
      notes-b64:
        description: 'Base64-encoded release notes (Markdown)'
        type: string

  workflow_dispatch:
    inputs:
      fail-on-no-release:
        description: 'Fail the workflow if no release is published (e.g. if there are no relevant commits).'
        type: boolean
        default: true
      publish:
        description: 'Whether to run in publish mode.'
        type: boolean
      tag:
        description: 'Existing release tag to publish (e.g. v1.2.3)'
        type: string
      notes-b64:
        description: 'Base64-encoded release notes (Markdown)'
        type: string

concurrency:
  group: '${{ github.repository_id }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}'
  cancel-in-progress: true

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  meta:
    name: Meta
    uses: ./.github/workflows/ci-meta.yaml
    permissions:
      contents: read
    with:
      publish: ${{ inputs.publish == true || (inputs.tag != '' && inputs.notes-b64 != '') }}

  release:
    name: Release
    needs: [meta]
    if: ${{ needs.meta.outputs.is-release-workflow == 'true' }}
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    with:
      dispatch-workflow: ${{ needs.meta.outputs.has-release-tags == 'false' && 'ci.yml' || '' }}
      fail-on-no-release: ${{ inputs.fail-on-no-release == true }}

  publish:
    name: Publish
    needs: [meta]
    if: ${{ needs.meta.outputs.is-publish-workflow == 'true' }}
    uses: ./.github/workflows/publish.yaml
    permissions:
      contents: write
    secrets: inherit
    with:
      tag: ${{ inputs.tag || github.ref_name }}
      notes-b64: ${{ inputs.notes-b64 }}

  normalize-majorver:
    name: Normalize Major Version Tag
    needs: [publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: stairwaytowonderland/normalize-majorver@v1
