name: CI

on:
  push:
    # Fires when a tag matching v* is pushed with personal credentials.
    tags: ['v*']
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:
    inputs:
      fail-on-no-release:
        description: 'Fail the workflow if no release is published (e.g. if there are no relevant commits).'
        type: boolean
        default: true
      publish:
        description: 'Whether to run in publish mode.'
        type: boolean
      dispatch-workflow:
        description: 'The workflow file to dispatch after a successful release.'
        type: boolean

concurrency:
  group: '${{ github.repository_id }}-${{ github.ref_name }}'
  cancel-in-progress: true

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      dispatch-workflow: ${{ steps.dispatch-workflow.outputs.dispatch-workflow }}
      publish: ${{ steps.determine-mode.outputs.publish }}
      release: ${{ steps.determine-mode.outputs.release }}
    steps:
      - name: Determine if release or publish mode should be used
        id: determine-mode
        run: |
          if [ "$IS_TAG" = 'true' ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
            echo "Release triggered by tag push, will run in 'publish' mode."
          elif [ "$IS_INPUT_PUBLISH" = 'true' ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
            echo "Release triggered by workflow dispatch with 'publish' enabled, will run in 'publish' mode."
          elif [ "$IS_RELEASE" = 'true' ]; then
            echo "release=true" >> $GITHUB_OUTPUT
            echo "Release triggered by push to default branch ('$DEFAULT_BRANCH') with 'publish' disabled, will run in 'release' mode and dispatch 'publish' workflow if a release is created."
          else
            echo "No 'release' or 'publish' triggered since it's not a tag push or a default branch push, and 'publish' isn't enabled."
          fi
        env:
          IS_TAG: ${{ startsWith(github.ref, 'refs/tags/v') }}
          IS_RELEASE: ${{ startsWith(github.ref, format('refs/heads/{0}', github.event.repository.default_branch)) && inputs.publish != 'true' }}
          IS_INPUT_PUBLISH: ${{ inputs.publish == 'true' }}

      - name: Determine dispatch workflow
        id: dispatch-workflow
        run: echo "dispatch-workflow=$DISPATCH_WORKFLOW" >> $GITHUB_OUTPUT
        env:
          DISPATCH_WORKFLOW: ${{ inputs.dispatch-workflow }}

  release:
    name: Release
    needs: [setup]
    if: ${{ needs.setup.outputs.release == 'true' }}
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    with:
      dispatch-workflow: ${{ needs.setup.outputs.dispatch-workflow }}
      fail-on-no-release: ${{ inputs.fail-on-no-release || false }}
      action-ref: 'main'

  publish:
    name: Publish
    needs: [setup]
    if: ${{ needs.setup.outputs.publish == 'true' }}
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      tag: ${{ github.ref_name }}
      action-ref: 'main'

  update-majorver:
    name: Update Major Version Tag
    needs: [publish]
    runs-on: ubuntu-latest
    steps:
      - uses: nowactions/update-majorver@v1
