name: Labels Create

on:
  workflow_dispatch:
    inputs:
      owner:
        description: 'GitHub organization or user that owns the repository'
        required: false
        type: string
      repo:
        description: 'GitHub repository name (if not the current repository)'
        required: false
        type: string
      dry-run:
        description: 'Dry run'
        required: true
        type: boolean
        default: true
      update-existing:
        description: 'Whether to update existing labels (e.g. rename, change color/description).'
        required: true
        type: boolean
        default: false
      ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        required: false
        type: string

jobs:
  create-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Checkout shared actions repo
        uses: actions/checkout@v6
        with:
          repository: stairwaytowonderland/actions
          ref: ${{ inputs.ref }}
          path: ./.actions
          sparse-checkout: |
            .github

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.ORG_REPO_USER_APP_ID }}
          private-key: ${{ secrets.ORG_REPO_USER_PRIVATE_KEY }}
          owner: ${{ inputs.owner || github.repository_owner }}
          repositories: ${{ inputs.repo || '' }}

      - name: Create labels
        uses: ./.actions/.github/actions/labels-create-action
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          owner: ${{ inputs.owner || github.event.repository.owner }}
          repo: ${{ inputs.repo || github.event.repository.name }}
          dry-run: ${{ inputs.dry-run == true }}
          update-existing: ${{ inputs.update-existing == true }}
