name: Normalize Major Version Tag

on:
  workflow_run:
    workflows: [ci.yaml]
    types: [completed]
  workflow_dispatch:
  workflow_call:
    secrets:
      github-token:
        description: 'GitHub Personal Access Token with repo scope for creating releases.'

permissions:
  contents: write

# Use PAT instead of GITHUB_TOKEN to cause semantic-release to trigger tag pipeline when tag is created.
# 'Fine-grained token' repo permissions: Contents

jobs:
  normalize-majorver:
    name: Normalize Major Version Tag
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (
        github.repository == 'stairwaytowonderland/actions' &&
        github.event.workflow_run.conclusion == 'success' &&
        startsWith(github.event.workflow_run.head_ref, 'refs/tags/')
      )
    steps:
      - uses: stairwaytowonderland/normalize-majorver@main
        with:
          github-token: ${{ secrets.github-token || github.token }}
