name: 🛰️ Labels Sync

on:
  workflow_dispatch:
    inputs:
      # org:
      #   description: 'GitHub organization to sync labels in (defaults to the organization of the repository this action is run in)'
      #   type: string
      dry-run:
        description: 'Dry run'
        type: boolean
        default: true
      update-existing:
        description: 'Whether to update existing labels (e.g. rename, change color/description).'
        type: boolean
      action-ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        type: string
        default: 'v1'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Checkout shared actions repo
        uses: actions/checkout@v7
        with:
          repository: stairwaytowonderland/actions
          path: ./.actions
          ref: ${{ inputs.action-ref }}
          persist-credentials: false
          sparse-checkout: |
            .github

      - name: Get repo info
        id: repo-info
        uses: ./.actions/.github/actions/repo-info-action

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.ORG_REPO_USER_APP_ID }}
          private-key: ${{ secrets.ORG_REPO_USER_PRIVATE_KEY }}
          owner: ${{ steps.repo-info.outputs.repo-owner }}

      - name: Sync labels
        uses: ./.actions/.github/actions/labels-sync-action
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          org: ${{ steps.repo-info.outputs.repo-owner }}
          dry-run: ${{ inputs.dry-run == true }}
          update-existing: ${{ inputs.update-existing == true }}
          repos: |
            actions
            cpython
            node-semantic-release
            resume-converter
            simple-workflow-dispatch
            ^cloudflare-.*$
            ^python-.*$
            ^repository-.*$
          repos-ignore: |
            ^\.github.*$
            ^deprecated-?.*$
            ^personal-?.*$
            ^.*-template$
