name: Watchers

on:
  workflow_call:
    inputs:
      create-issue:
        description: 'Whether to create a welcome issue for the watcher (if they are a member of the organization).'
        type: boolean
        required: false

      exclude:
        description: 'Repos to exclude from watcher handling.'
        type: string
        required: false
        # default: |
        #   ${{ format('{0}/repository-template', github.repository_owner) }}

      job-summary:
        description: 'Whether to add a job summary with the welcome message for the watcher.'
        type: boolean
        required: false
        default: true

      ref:
        description: 'Git ref of the shared actions repo to use (e.g. main or a specific tag/commit)'
        type: string
        required: false
        default: 'v1'

    outputs:
      message-heading:
        description: 'The heading of the welcome message created for the watcher.'
        value: ${{ jobs.on-watch.outputs.message-heading }}
      message-body-base64:
        description: 'The body of the welcome message created for the watcher, encoded in base64.'
        value: ${{ jobs.on-watch.outputs.message-body-base64 }}
      is-organization-member:
        description: 'Whether the watcher is a member of the organization.'
        value: ${{ jobs.on-watch.outputs.is-organization-member }}

    secrets:
      github-token:
        description: 'GitHub Personal Access Token with repo scope for creating issues.'
        required: false

jobs:
  on-watch:
    name: Watching the watchers
    # if: inputs.exclude == '' || (inputs.exclude != '' && !contains(inputs.exclude, github.repository))
    if: inputs.exclude == '' || (inputs.exclude != '' && inputs.exclude != github.repository)
    runs-on: ubuntu-latest
    outputs:
      message-heading: ${{ steps.on-watch.outputs.message-heading }}
      message-body-base64: ${{ steps.on-watch.outputs.message-body-base64 }}
      is-organization-member: ${{ steps.on-watch.outputs.is-organization-member }}
    steps:
      - name: Checkout shared actions repo
        uses: actions/checkout@v7
        with:
          repository: stairwaytowonderland/actions
          ref: ${{ inputs.ref }}
          path: ./.actions
          sparse-checkout: |
            .github

      - name: On Watch
        id: on-watch
        uses: ./.actions/.github/actions/watchers
        with:
          create-issue: ${{ inputs.create-issue == true }}
          job-summary: ${{ inputs.job-summary == true }}
          github-token: ${{ secrets.github-token || secrets.GH_PAT_REPO_WRITE }}

      - name: Job Summary
        if: inputs.job-summary != true && steps.on-watch.outputs.is-organization-member == 'true'
        env:
          MESSAGE_HEADING: ${{ steps.on-watch.outputs.message-heading }}
          MESSAGE_BODY_BASE64: ${{ steps.on-watch.outputs.message-body-base64 }}
        run: |
          MESSAGE_BODY=$(printf '%s' "$MESSAGE_BODY_BASE64" | base64 -d)
          tee -a "$GITHUB_STEP_SUMMARY" <<EOF
          ## ${MESSAGE_HEADING}

          ${MESSAGE_BODY}
          EOF
